"""PDF report generation using ReportLab."""

import io
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    Image,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

BRAND_BLUE = colors.HexColor("#2E5090")
BRAND_ORANGE = colors.HexColor("#E8833A")
LIGHT_GREY = colors.HexColor("#F5F5F5")
WIDTH, HEIGHT = A4


def _styles() -> dict:
    ss = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle", parent=ss["Title"],
            fontSize=28, leading=34, textColor=BRAND_BLUE,
            spaceAfter=6 * mm, alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle", parent=ss["Normal"],
            fontSize=12, leading=16, textColor=colors.grey,
            spaceAfter=20 * mm, alignment=TA_CENTER,
        ),
        "heading": ParagraphStyle(
            "SectionHeading", parent=ss["Heading1"],
            fontSize=16, leading=20, textColor=BRAND_BLUE,
            spaceBefore=10 * mm, spaceAfter=4 * mm,
        ),
        "body": ParagraphStyle(
            "BodyText", parent=ss["BodyText"],
            fontSize=10, leading=14, alignment=TA_JUSTIFY,
            spaceAfter=3 * mm,
        ),
        "table_header": ParagraphStyle(
            "TableHeader", parent=ss["Normal"],
            fontSize=9, leading=12, textColor=colors.white,
            alignment=TA_CENTER,
        ),
        "table_cell": ParagraphStyle(
            "TableCell", parent=ss["Normal"],
            fontSize=9, leading=12, alignment=TA_CENTER,
        ),
        "table_cell_left": ParagraphStyle(
            "TableCellLeft", parent=ss["Normal"],
            fontSize=9, leading=12, alignment=TA_LEFT,
        ),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    # Header line
    canvas.setStrokeColor(BRAND_BLUE)
    canvas.setLineWidth(1.5)
    canvas.line(2 * cm, HEIGHT - 1.5 * cm, WIDTH - 2 * cm, HEIGHT - 1.5 * cm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(2 * cm, HEIGHT - 1.3 * cm, "CONFIDENTIAL — Sample Investment Report")
    # Footer
    canvas.line(2 * cm, 1.8 * cm, WIDTH - 2 * cm, 1.8 * cm)
    canvas.drawString(2 * cm, 1.2 * cm, "Generated by Reporting Engine")
    canvas.drawRightString(WIDTH - 2 * cm, 1.2 * cm, f"Page {doc.page}")
    canvas.restoreState()


def _build_table(df, styles: dict) -> Table:
    """Convert a DataFrame into a styled ReportLab Table."""
    header = [Paragraph(str(c), styles["table_header"]) for c in df.columns]
    rows = [header]
    for _, row in df.iterrows():
        cells = []
        for i, val in enumerate(row):
            style = styles["table_cell_left"] if i == 0 else styles["table_cell"]
            cells.append(Paragraph(str(val), style))
        rows.append(cells)

    col_widths = [4.5 * cm] + [3.0 * cm] * (len(df.columns) - 1)
    tbl = Table(rows, colWidths=col_widths, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ALIGN", (0, 1), (0, -1), "LEFT"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return tbl


def _chart_image(chart_buf_or_path, width=14 * cm) -> Image:
    """Create an Image flowable from a file path or BytesIO buffer."""
    if isinstance(chart_buf_or_path, io.BytesIO):
        chart_buf_or_path.seek(0)
    return Image(chart_buf_or_path, width=width, height=width * 0.57)


def generate_pdf(
    charts: dict[str, str | io.BytesIO],
    holdings_df,
    commentary: dict,
    output_path: str = "output/report.pdf",
) -> str:
    """Build the full PDF report."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    styles = _styles()

    frame = Frame(2 * cm, 2.5 * cm, WIDTH - 4 * cm, HEIGHT - 4.5 * cm, id="main")
    template = PageTemplate(id="standard", frames=frame, onPage=_header_footer)
    doc = BaseDocTemplate(output_path, pagesize=A4, pageTemplates=[template])

    story = []

    # --- Cover / Title ---
    story.append(Spacer(1, 6 * cm))
    story.append(Paragraph("Quarterly Investment Report", styles["title"]))
    story.append(Paragraph("Q4 2024 — Sample Fund", styles["subtitle"]))
    story.append(PageBreak())

    # --- Executive Summary ---
    story.append(Paragraph("Executive Summary", styles["heading"]))
    story.append(Paragraph(commentary["executive_summary"], styles["body"]))

    # --- Performance Section ---
    story.append(Paragraph("Performance Overview", styles["heading"]))
    perf_text = commentary.get(
        "performance_commentary",
        "The chart below shows cumulative portfolio performance against the "
        "composite benchmark over the trailing four-year period.",
    )
    story.append(Paragraph(perf_text, styles["body"]))
    story.append(_chart_image(charts["line_chart"]))
    story.append(Spacer(1, 5 * mm))

    story.append(Paragraph("Return Distribution", styles["heading"]))
    dist_text = commentary.get(
        "return_distribution_commentary",
        "Monthly return distribution exhibits a slight positive skew, consistent "
        "with the portfolio's quality tilt and downside protection strategies.",
    )
    story.append(Paragraph(dist_text, styles["body"]))
    story.append(_chart_image(charts["histogram"]))
    story.append(PageBreak())

    # --- Asset Allocation ---
    story.append(Paragraph("Asset Allocation", styles["heading"]))
    alloc_text = commentary.get(
        "allocation_commentary",
        "Strategic asset allocation evolved over the period to reflect changing "
        "market conditions and the investment committee's outlook adjustments.",
    )
    story.append(Paragraph(alloc_text, styles["body"]))
    story.append(_chart_image(charts["stacked_area"]))
    story.append(Spacer(1, 5 * mm))

    # --- Holdings Table ---
    story.append(Paragraph("Top Holdings", styles["heading"]))
    holdings_text = commentary.get("holdings_commentary", "")
    if holdings_text:
        story.append(Paragraph(holdings_text, styles["body"]))
    story.append(_build_table(holdings_df, styles))
    story.append(PageBreak())

    # --- Risk Assessment ---
    story.append(Paragraph("Risk Assessment", styles["heading"]))
    story.append(Paragraph(commentary["risk_assessment"], styles["body"]))
    story.append(_chart_image(charts["spider_chart"], width=12 * cm))
    story.append(Spacer(1, 5 * mm))

    # --- Market Outlook ---
    story.append(Paragraph("Market Outlook", styles["heading"]))
    story.append(Paragraph(commentary["market_outlook"], styles["body"]))

    doc.build(story)
    return output_path
