"""Theme loader and defaults.

A theme is a JSON file in themes/ that defines colors, fonts, logos, and
branding text. Every rendering function accepts an optional theme dict;
when None, DEFAULT_THEME is used so existing code keeps working.
"""

import json
from pathlib import Path

THEMES_DIR = Path(__file__).parent / "themes"

DEFAULT_THEME: dict = {
    "theme_id": "default",
    "client_name": "",
    "logo": None,
    "colors": {
        "primary": "#2E5090",
        "secondary": "#E8833A",
        "accent": "#4CAF50",
        "text_dark": "#333333",
        "text_light": "#F5F5F5",
        "background_alt": "#F5F5F5",
        "grid": "#DDDDDD",
    },
    "chart_palette": ["#2E5090", "#E8833A", "#4CAF50", "#9C27B0", "#F44336", "#00BCD4"],
    "fonts": {
        "heading": "Helvetica-Bold",
        "body": "Helvetica",
        "mono": "Courier",
    },
    "pdf": {
        "header_text": "CONFIDENTIAL — Investment Report",
        "footer_text": "Generated by Reporting Engine",
    },
    "pptx": {
        "title_slide_bg": "#2E5090",
        "section_slide_bg": "#2E5090",
    },
}


def list_themes() -> list[dict]:
    """Return summary for all available themes."""
    themes = [{"theme_id": "default", "client_name": "(built-in default)"}]
    for path in sorted(THEMES_DIR.glob("*.json")):
        t = json.loads(path.read_text())
        themes.append({
            "theme_id": t["theme_id"],
            "client_name": t.get("client_name", ""),
        })
    return themes


def load_theme(theme_id: str | None) -> dict:
    """Load a theme by ID. Returns DEFAULT_THEME when theme_id is None or 'default'."""
    if not theme_id or theme_id == "default":
        return DEFAULT_THEME.copy()

    path = THEMES_DIR / f"{theme_id}.json"
    if not path.exists():
        available = [p.stem for p in THEMES_DIR.glob("*.json")]
        raise FileNotFoundError(
            f"Theme '{theme_id}' not found. Available: {['default'] + available}"
        )
    # Merge with defaults so missing keys still work
    theme = DEFAULT_THEME.copy()
    loaded = json.loads(path.read_text())
    theme.update(loaded)
    theme["colors"] = {**DEFAULT_THEME["colors"], **loaded.get("colors", {})}
    theme["fonts"] = {**DEFAULT_THEME["fonts"], **loaded.get("fonts", {})}
    theme["pdf"] = {**DEFAULT_THEME["pdf"], **loaded.get("pdf", {})}
    theme["pptx"] = {**DEFAULT_THEME["pptx"], **loaded.get("pptx", {})}
    return theme
